# EMC controller parameters for a simulated machine.
# General note: Comments can either be preceded with a # or ; - either is
# acceptable, although # is in keeping with most linux config files.

# General section -------------------------------------------------------------
[EMC]
VERSION = 1.1
MACHINE =               gmoccapy_lathe
#DEBUG =               0x7FFFFFFF
DEBUG = 0

# for details see nc_files/subroutines/maco_instructions.txt
[DISPLAY]
	DISPLAY = gmoccapy
	LATHE = 1
	BACK_TOOL_LATHE = 0
	EMBED_TAB_NAME = Spindle_load
	EMBED_TAB_LOCATION = box_custom_4
	EMBED_TAB_COMMAND = gladevcp -x {XID} -H spindle_load.hal spindle_load.glade 

	EMBED_TAB_NAME = Not_cool
	EMBED_TAB_LOCATION = box_cooling
	EMBED_TAB_COMMAND = hide
	EMBED_TAB_NAME = Drive_status
	EMBED_TAB_LOCATION = hbox_jog
	EMBED_TAB_COMMAND = gladevcp -x {XID} -H drive_status.hal drive_status.glade 

	# Cycle time, in milliseconds, that display will sleep between polls
	CYCLE_TIME =            100

	# Highest value that will be allowed for feed override, 1.0 = 100%
	MAX_FEED_OVERRIDE =     1.5
	MAX_SPINDLE_OVERRIDE =  1.2
	MIN_SPINDLE_OVERRIDE = .5

	# Prefix to be used
	PROGRAM_PREFIX = ~/nc_files/

	# Introductory graphic
	INTRO_GRAPHIC = 
	INTRO_TIME = 5

	# list of selectable jog increments
	INCREMENTS = 0.100 mm, 0.010 mm, 0.001 mm

[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Grayscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python3

[XHC_HB04_CONFIG]
	# specify layout = n for LIB:xhc-hb04-layout{n}.cfg files
	layout = 2
	# coords: specify upto 4 letters from set {x y z a b c u v w}
	# coords: switch labels are xyza but any unique 4 letters
	#         from the set {xyxabcuvw) can be used (if the coord exists)
	coords = x z
	# lowpass settings:
	# coef: slows rate of change of output,  range: 0 < coef < 1
	coefs = 1 1 1 1
	# scale plus or minus, rotaries may require larger scale factor:
	scales = -1 1 1 1
	# jogmode normal(default) or vnormal
	jogmode = normal
	# sequence 1: 0.001,0.010,0.100,1.000 (mm-based machine)
	# sequence 2: 0.001,0.005,0.010,0.020 (inch-based machine)
	# sequence 3: 0.001,0.010,0.100
	# sequence 4: 0.001,0.005,0.010,0.020,0.050,0.100
	# sequence 5: 0.001,0.010,0.050,0.100,1.000
	sequence = 1
	# require_pendant = yes|no: create xhc-hb04 hal pins when pendant not
	#                           connected at startup
	require_pendant = no
	# inch_or_mm = in | mm
	inch_or_mm = mm
	# mpg_accels: provision for reduced acceleration for manual mode jogging
	mpg_accels = 300 300 300 300

[APPLICATIONS]
	APP = monitor-xhc-hb04

# Task controller section -----------------------------------------------------
[RS274NGC]
RS274NGC_STARTUP_CODE = G18 G21 G40 G49 G54 G80 G90 G94 G7 M9 M5 G64 P0.005
PARAMETER_FILE = sim.var
SUBROUTINE_PATH = macros

# Motion control section ------------------------------------------------------
[EMCMOT]
EMCMOT =              motmod
COMM_TIMEOUT =          1.0
BASE_PERIOD  =          100000
SERVO_PERIOD =          1000000

# Hardware Abstraction Layer section --------------------------------------------------
[TASK]
TASK =                  milltask
CYCLE_TIME =            0.001

# Part program interpreter section --------------------------------------------
[HAL]
HALFILE = core_sim_lathe.hal
HALFILE = spindle_sim.hal
HALFILE = simulated_home_lathe.hal
HALFILE = LIB:xhc-hb04.tcl

# Single file that is executed after the GUI has started.
POSTGUI_HALFILE = gmoccapy_postgui.hal

HALUI = halui

# Trajectory planner section --------------------------------------------------
[HALUI]
# these are examples, edit as required:
# a halui hal pin is created for each MDI_COMMAND below
# halui.mdi-command-00, halui.mdi-command-01,... etc
# Gele knop, waypoint
MDI_COMMAND=#<waypoint_x>=#<_x>
# Macro-1
MDI_COMMAND=o<face> call
# Macro-2
MDI_COMMAND=o<simple_cycle> call [#<waypoint_x>] [#<waypoint_z>]
# Macro 3
MDI_COMMAND=(debug, example: mdi-03)
# mdi-04, Waypoint voor Z
MDI_COMMAND=#<waypoint_z>=#<_z>
MDI_COMMAND=(debug, example: mdi-05)
# Macro 6
MDI_COMMAND=(debug, example: mdi-06)
#Macro 7
MDI_COMMAND=(debug, example: mdi-07)
MDI_COMMAND=(debug, example: mdi-08)
MDI_COMMAND=(debug, example: mdi-09)
# Safe-z
MDI_COMMAND=(debug, example: mdi-10)
MDI_COMMAND=(debug, example: mdi-11)

MDI_COMMAND= G10 L20 P0 X0
MDI_COMMAND= G10 L20 P0 Y0
MDI_COMMAND= G10 L20 P0 Z0
MDI_COMMAND= G10 L20 P0 C0
#No Content

[TRAJ]
COORDINATES =      X Z
LINEAR_UNITS =     mm
ANGULAR_UNITS =    degree
DEFAULT_LINEAR_VELOCITY = 50
MAX_LINEAR_VELOCITY = 234
POSITION_FILE =    position.txt
#NO_FORCE_HOMING = 1

# First axis
[EMCIO]
EMCIO = 		io
CYCLE_TIME =    0.100

# tool table file
TOOL_TABLE = lathe.tbl

[KINS]
KINEMATICS = trivkins coordinates=XZ
JOINTS = 2

[AXIS_X]
MIN_LIMIT = -50.0
MAX_LIMIT = 200.0
MAX_VELOCITY = 166
MAX_ACCELERATION = 1500.0

[JOINT_0]
TYPE =                          LINEAR
MAX_VELOCITY =                  166
MAX_ACCELERATION =              1500.0
BACKLASH = 0.000
INPUT_SCALE =                   4000
OUTPUT_SCALE = 1.000
MIN_LIMIT =                     -50.0
MAX_LIMIT =                     200.0
FERROR = 0.050
MIN_FERROR = 0.010
HOME_OFFSET =                    0.0
HOME =                           100
HOME_SEARCH_VEL =                200.0
HOME_LATCH_VEL =                 20.0
HOME_USE_INDEX =                 NO
HOME_IGNORE_LIMITS =             NO
HOME_SEQUENCE = 1
HOME_IS_SHARED = 1

# Third axis
[AXIS_Z]
MIN_LIMIT = -75.0
MAX_LIMIT = 1000.0
MAX_VELOCITY = 166
MAX_ACCELERATION = 1500.0

[JOINT_1]
TYPE =                          LINEAR
MAX_VELOCITY =                  166
MAX_ACCELERATION =              1500.0
BACKLASH = 0.000
INPUT_SCALE =                   4000
OUTPUT_SCALE = 1.000
MIN_LIMIT =                     -75.0
MAX_LIMIT =                     1000.0
FERROR = 0.050
MIN_FERROR = 0.010
HOME_OFFSET =                    1.0
HOME =                           250
HOME_SEARCH_VEL =                200.0
HOME_LATCH_VEL =                 20.0
HOME_USE_INDEX =                 NO
HOME_IGNORE_LIMITS =             NO
HOME_SEQUENCE = 0
HOME_IS_SHARED = 1

# section for main IO controller parameters -----------------------------------
[MACROS]
MACRO = thread major pitch start-z end-z
MACRO = external final z

#INCLUDE layout2.inc
