[EMC]
	VERSION = 1.1
	MACHINE = HBM 280 gmoccapy
	DEBUG = 0

[DISPLAY]
	DISPLAY = gmoccapy
	PYVCP = lathe.xml
	LATHE = 1
	CYCLE_TIME = 100
	POSITION_OFFSET = RELATIVE
	POSITION_FEEDBACK = ACTUAL
	MAX_FEED_OVERRIDE = 1.2
	MAX_SPINDLE_OVERRIDE = 1.0
	PROGRAM_PREFIX = /home/mark/nc_files/
	EMBED_TAB_NAME = Spindle_load
	EMBED_TAB_LOCATION = box_custom_4
	EMBED_TAB_COMMAND = gladevcp -x {XID} -H spindle_load.hal spindle_load.glade 
	EMBED_TAB_NAME = Drive_status
	EMBED_TAB_LOCATION = hbox_jog
	EMBED_TAB_COMMAND = gladevcp -x {XID} -H drive_status.hal drive_status.glade
	LINEAR_INCREMENTS = 1.000 mm, 0.100 mm, 0.010 mm, 0.001 mm
	MIN_LINEAR_VELOCITY = 0
	MAX_LINEAR_VELOCITY = 50
	DEFAULT_SPINDLE_0_SPEED = 200
	MIN_SPINDLE_0_SPEED = 20
	MAX_SPINDLE_0_SPEED = 1700
	MIN_SPINDLE_0_OVERRIDE = 0.5
	MAX_SPINDLE_0_OVERRIDE = 1.2
	MIN_ANGULAR_VELOCITY = 0.1
	DEFAULT_ANGULAR_VELOCITY = 360
	MAX_ANGULAR_VELOCITY =  3600
	DEFAULT_SPINDLE_SPEED = 300
	MIN_SPINDLE_OVERRIDE = 0.5
	DEFAULT_LINEAR_VELOCITY = 25


[HAL]
	HALUI = halui
        HALFILE = ./lathe_cmds.hal
        HALFILE = LIB:xhc-hb04.tcl
        HALFILE = gmoccapy.hal
        POSTGUI_HALFILE = gmoccapy_postgui.hal



#INCLUDE base.inc
#INCLUDE layout2.inc
