[EMC]
	VERSION = 1.1
	MACHINE = LinuxCNC-HAL-SIM-LATHE
	DEBUG = 0

[DISPLAY]
	DISPLAY = axis
	PYVCP = lathe.xml
	LATHE = 1
	CYCLE_TIME = 0.100
	POSITION_OFFSET = RELATIVE
	POSITION_FEEDBACK = ACTUAL
	MAX_FEED_OVERRIDE = 1.2
	MAX_SPINDLE_OVERRIDE = 1.0
	PROGRAM_PREFIX = /home/mark/nc_files/

[HAL]
	HALUI = halui
        HALFILE = ./lathe_cmds.hal
        HALFILE = LIB:xhc-hb04.tcl
        POSTGUI_HALFILE = lathe_postgui.hal


#INCLUDE base.inc
#INCLUDE layout2.inc
