[EMC]
	VERSION = 1.1
	MACHINE = LinuxCNC-HAL-SIM-LATHE
	DEBUG = 0

[DISPLAY]
	DISPLAY = axis
	LATHE = 1
	CYCLE_TIME = 0.100
	POSITION_OFFSET = RELATIVE
	POSITION_FEEDBACK = ACTUAL
	MAX_FEED_OVERRIDE = 1.2
	MAX_SPINDLE_OVERRIDE = 1.0
	PROGRAM_PREFIX = /home/mark/nc_files/

[FILTER]
	PROGRAM_EXTENSION = .png,.gif,.jpg Grayscale Depth Image
	PROGRAM_EXTENSION = .py Python Script
	png = image-to-gcode
	gif = image-to-gcode
	jpg = image-to-gcode
	py = python

[RS274NGC]
	PARAMETER_FILE = sim-lathe.var

[EMCMOT]
	EMCMOT = motmod
	COMM_TIMEOUT = 1.0
	SERVO_PERIOD = 222222

[TASK]
	TASK = milltask
	CYCLE_TIME = 0.001

[HAL]
	HALUI = halui
	#HALFILE = LIB:basic_sim.tcl
        HALFILE = ./lathe_cmds.hal

[TRAJ]
	COORDINATES = X Z
	LINEAR_UNITS = mm
	ANGULAR_UNITS = degree
	DEFAULT_LINEAR_VELOCITY = 5.0
	MAX_LINEAR_VELOCITY = 50.0
	DEFAULT_LINEAR_ACCELERATION = 1500.0
	MAX_LINEAR_ACCELERATION = 1500.0

[EMCIO]
	EMCIO = io
	CYCLE_TIME = 0.100
	TOOL_TABLE = lathe.tbl
	TOOL_CHANGE_POSITION = 2 0 1
	TOOL_CHANGE_WITH_SPINDLE_ON = 1

[KINS]
	KINEMATICS = trivkins coordinates=xz
	JOINTS = 2

[AXIS_X]
	MIN_LIMIT = -100.0
	MAX_LIMIT = 100.0
	MAX_VELOCITY = 50.0
	MAX_ACCELERATION = 8000000.0

[JOINT_0]
	TYPE = LINEAR
	MAX_VELOCITY = 50.0
	MAX_ACCELERATION = 8000.0
	MIN_LIMIT = -100.0
	MAX_LIMIT = 100.0
	HOME_SEARCH_VEL = 5.0
	HOME_LATCH_VEL = 1.0
	HOME_SEQUENCE = 0

[AXIS_Z]
	MIN_LIMIT = -20.0
	MAX_LIMIT = 400.0
	MAX_VELOCITY = 50.0
	MAX_ACCELERATION = 8000.0

[JOINT_1]
	TYPE = LINEAR
	MAX_VELOCITY = 50.0
	MAX_ACCELERATION = 8000.0
	MIN_LIMIT = -20.0
	MAX_LIMIT = 400.0
	HOME_SEARCH_VEL = 5.0
	HOME_LATCH_VEL = 1.0
	HOME_SEQUENCE = 1
